# joint_limits.yaml allows overriding limits specified in the URDF
# or adding limits not specified in the URDF
# Specific joint properties can be changed with the format:
# joint_limits:
#   joint_name:
#     has_position_limits: true
#     min_position: 0
#     max_position: 1
#     has_velocity_limits: true
#     max_velocity: 2
#     has_acceleration_limits: true
#     max_acceleration: 5
#     has_jerk_limits: false
#     max_jerk: 0


joint_limits:
  joint0:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 1.0  # From URDF
    has_acceleration_limits: true
    max_acceleration: 1.0 # Default value
  joint1:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 1.0  # From URDF
    has_acceleration_limits: true
    max_acceleration: 1.0 # Default value
  joint2:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 1.0  # From URDF
    has_acceleration_limits: true
    max_acceleration: 1.0 # Default value 