moveit_simple_controller_manager:
  controller_names:
    - arm_trajectory_controller

  arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      # - joint2 