planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0  # Max motion added to tree. If 0.0, server will decide.
  # Add more planners if needed

arm_group: # Matches the group name in SRDF
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(joint0,joint1)
  longest_valid_segment_fraction: 0.05

# Default planner parameters
default_planner_config: RRTConnect 