controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    arm_position_controller:
      type: forward_command_controller/ForwardCommandController

# joint_state_broadcaster:
#   ros__parameters:
#     type: joint_state_broadcaster/JointStateBroadcaster


arm_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint0
      - joint1
      - joint2
    interface_name: position